apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-system

spec:
  type: ClusterIP

  ports:
    - name: api
      port: 3000
      targetPort: api
    - name: api-debug
      port: 3010
      targetPort: api-debug
    - name: metrics
      port: 4000
      targetPort: metrics
    - name: metrics-debug
      port: 4010
      targetPort: metrics-debug
    - name: prometheus
      port: 4020
      targetPort: metrics-prom
