apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api-system

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
        - name: api
          resources:
            requests:
              cpu: '250m'
              memory: '100Mi'
            limits:
              cpu: '250m'
              memory: '100Mi'

        - name: metrics
          resources:
            requests:
              cpu: '250m'
            limits:
              cpu: '250m'
