apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/api/
  - ./dev-api-configmap.yaml
patches:
  - path: ./dev-api-patch-deploy.yaml
  - path: ./dev-api-patch-service.yaml
images:
  - name: api-image
    newName: localhost/hexagonal-project/api
    newTag: 0.0.1
